# Generated by Django 2.2.28 on 2023-11-12 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipements',
            fields=[
                ('id_equipement', models.AutoField(choices=[('Zone_d_attente', "Zone d'attente"), ('Zone_de_livraison', 'Zone de livraison'), ('Atelier_de_répartition', 'Atelier de répartition'), ('Atelier_de_diagnostic', 'Atelier de diagnostic')], primary_key=True, serialize=False)),
                ('etat_equ', models.CharField(choices=[('Zone_d_attente', "Zone d'attente"), ('Zone_de_livraison', 'Zone de livraison'), ('Atelier_de_répartition', 'Atelier de répartition'), ('Atelier_de_diagnostic', 'Atelier de diagnostic')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('etat', models.CharField(choices=[('bon_etat', 'En bon état'), ('en_diagnostic', 'En diagnostic'), ('en_reparation', 'En réparation'), ('en_attente_piece', 'En attente de pièces')], max_length=100)),
                ('type', models.CharField(choices=[('voiture', 'Voiture'), ('moto', 'Moto'), ('camion', 'Camion')], max_length=100)),
                ('marque', models.CharField(max_length=200)),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Equipements')),
            ],
        ),
    ]
