# Generated by Django 2.2.28 on 2023-11-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipements',
            name='etat_equ',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupé', 'Occupé')], max_length=100),
        ),
    ]
