# Generated by Django 2.2.28 on 2023-11-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231112_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipements',
            name='nom_equi',
            field=models.CharField(choices=[('Zone_d_attente', "Zone d'attente"), ('Zone_de_livraison', 'Zone de livraison'), ('Atelier_de_répartition', 'Atelier de répartition'), ('Atelier_de_diagnostic', 'Atelier de diagnostic')], default='__', max_length=200),
        ),
        migrations.AlterField(
            model_name='equipements',
            name='id_equipement',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
