# Generated by Django 2.2.28 on 2023-11-13 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20231112_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
